version: '3.8'

services:
  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_DB: dam_stats_db
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  web:
    build: .
    container_name: django_web
    command: gunicorn dam_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      POSTGRES_DB: dam_db
      POSTGRES_USER: dam_user
      POSTGRES_PASSWORD: dam_password
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network: