# Generated by Django 5.1 on 2024-08-15 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dams', '0002_district_rename_damstatistic_damstatistics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='damstatistics',
            old_name='powerhouse_discharge',
            new_name='power_house_discharge',
        ),
        migrations.AlterField(
            model_name='dam',
            name='district',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dam',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='damstatistics',
            name='dam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='dams.dam'),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
