# Generated by Django 5.1 on 2024-08-16 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dams', '0003_rename_powerhouse_discharge_damstatistics_power_house_discharge_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='District',
        ),
        migrations.AlterField(
            model_name='dam',
            name='district',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='dam',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='damstatistics',
            name='inflow',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='damstatistics',
            name='power_house_discharge',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='damstatistics',
            name='rainfall',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='damstatistics',
            name='spillway_release',
            field=models.FloatField(),
        ),
    ]
