name: build_and_deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests with coverage
      run: |
        pip install coverage
        coverage run -m django test
        coverage report

    - name: Run Bandit
      run: |
        pip install bandit
        bandit -r dams/  # Updated with your actual app directory

    - name: Check for vulnerabilities
      run: |
        pip install safety
        safety check -r requirements.txt
