name: Docker Image CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/django-damproject:latest .
          docker tag ${{ secrets.akashkrishna25 }}/django-damproject:latest ${{ secrets.akashkrishna25}/django-damproject:${{ github.sha }}
          docker push ${{ secrets.akashkrishna25}}/django-damproject:latest
          docker push ${{ secrets.akashkrishna25}}/django-damproject:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to Production Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.ubuntu }}@${{ secrets.192.168.1.100 }} << 'EOF'
            docker pull ${{ secrets.DOCKER_USERNAME }}/django-damproject:latest
            docker-compose -f /path/to/docker-compose.prod.yml up -d --no-deps --build web
          EOF
