name: build_and_deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: dam_stats_db
          POSTGRES_USER: your_db_user
          POSTGRES_PASSWORD: your_db_password
        ports:
          - 5432:5432
        options: > 
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Wait for PostgreSQL to be ready
      run: |
        until pg_isready -h 127.0.0.1 -p 5432; do
          echo "Waiting for PostgreSQL to be ready..."
          sleep 2
        done

    - name: Set up Django environment
      env:
        DB_NAME: dam_stats_db
        DB_USER: your_db_user
        DB_PASSWORD: your_db_password
        DB_HOST: 127.0.0.1
        DB_PORT: 5432
      run: |
        python manage.py migrate
        python manage.py collectstatic --noinput

    - name: Run tests
      run: |
        python manage.py test

    - name: Complete job
      run: echo "CI/CD pipeline completed successfully."
