name: build_and_deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Set up Django environment
      env:
        DB_NAME: dam_stats_db
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_HOST: 127.0.0.1
        DB_PORT: 5432
      run: |
        python manage.py migrate
        python manage.py collectstatic --noinput

    - name: Run tests
      run: |
        python manage.py test

    # Other steps to build, deploy, etc.
