name: build_and_deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests with coverage
      env:
        DJANGO_SETTINGS_MODULE: dam_project.settings  # Update with your actual settings module path
      run: |
        pip install coverage
        coverage run -m django test
        coverage report

    - name: Run Bandit
      run: |
        pip install bandit
        # Running Bandit with severity levels to get a more detailed output
        bandit -r dams/ -ll

    - name: Check for vulnerabilities
      run: |
        pip install safety
        safety check -r requirements.txt

    - name: Check PEP 8 compliance with Flake8
      run: |
        pip install flake8
        # Set max line length to 79 and ignore specific rules
        flake8 --max-line-length=79 --ignore=E501 dam_project/
